# Example of the Cloud Build template usage.
#
# In this example, a sample NodeJS "Hello World" app container is built and pushed to
# the container registry.
#
# The Build steps are as follows:
#  Step1: Clone the cloud-builders GitHub repository
#  Step2: Build the Docker image from Dockerfile in the npm/examples/hello_world dir
#  Step3: Tag the image as gcr.io/$PROJECT_ID/${_IMAGE_NAME}
#  Step4: Push the image to the container registry gcr.io/$PROJECT_ID/${_IMAGE_NAME}

imports:
  - path: cloudbuild.py
    name: build.py

resources:
  - name: mycloudbuild
    type: build.py
    properties:
      steps:
        # Step 1
        - name: 'gcr.io/cloud-builders/git'
          args:
            - clone
            - https://github.com/ONSdigital/eq-gcp-deployment-manager-poc.git
        # Step 2
        - name: 'gcr.io/cloud-builders/docker'
          args:
            - build
            # Step 3
            - '--tag=gcr.io/$PROJECT_ID/${_IMAGE_NAME}'
            - '.'
          dir: eq-gcp-deployment-manager-poc
        # Step 4
        - name: 'gcr.io/cloud-builders/docker'
          args:
            - push
            - 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}'
      substitutions:
        _IMAGE_NAME: npm-helloworld
      images:
        - 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}'
      timeout: '200s'
